=== TheGhostGroup/aion-germany/AL-Game/data/static_data/luna/luna_bonusattr.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
	<xs:include schemaLocation="../modifiers.xsd"/>
	<xs:element name="luna_bonusattrs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="luna_bonusattr" type="LunaBonusServiceAttr" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="LunaBonusServiceAttr">
		<xs:sequence>
			<xs:element name="bonus_attr" type="LunaBonusAttr" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="buff_id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="LunaBonusAttr">
		<xs:attribute name="stat" type="modifiersenum" use="required"/>
		<xs:attribute name="func" type="StatFunc" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/luna/luna_bonusattr.xml
<?xml version="1.0" encoding="UTF-8"?>
<luna_bonusattrs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="luna_bonusattr.xsd">
	<luna_bonusattr buff_id="7">
		<bonus_attr stat="MAXHP" func="ADD" value="100"/>
		<bonus_attr stat="MAXMP" func="ADD" value="70"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="10"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="18"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="18"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="18"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="18"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="100"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="100"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="55"/>
		<bonus_attr stat="BLOCK" func="ADD" value="55"/>
		<bonus_attr stat="PARRY" func="ADD" value="55"/>
		<bonus_attr stat="EVASION" func="ADD" value="55"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="55"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="55"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="8">
		<bonus_attr stat="MAXHP" func="ADD" value="154"/>
		<bonus_attr stat="MAXMP" func="ADD" value="108"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="12"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="22"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="22"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="22"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="22"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="110"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="110"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="66"/>
		<bonus_attr stat="BLOCK" func="ADD" value="66"/>
		<bonus_attr stat="PARRY" func="ADD" value="66"/>
		<bonus_attr stat="EVASION" func="ADD" value="66"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="66"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="66"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="9">
		<bonus_attr stat="MAXHP" func="ADD" value="208"/>
		<bonus_attr stat="MAXMP" func="ADD" value="146"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="15"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="26"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="26"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="26"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="26"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="120"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="120"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="78"/>
		<bonus_attr stat="BLOCK" func="ADD" value="78"/>
		<bonus_attr stat="PARRY" func="ADD" value="78"/>
		<bonus_attr stat="EVASION" func="ADD" value="78"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="78"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="78"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="10">
		<bonus_attr stat="MAXHP" func="ADD" value="263"/>
		<bonus_attr stat="MAXMP" func="ADD" value="184"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="17"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="30"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="30"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="30"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="30"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="129"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="129"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="89"/>
		<bonus_attr stat="BLOCK" func="ADD" value="89"/>
		<bonus_attr stat="PARRY" func="ADD" value="89"/>
		<bonus_attr stat="EVASION" func="ADD" value="89"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="89"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="89"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="11">
		<bonus_attr stat="MAXHP" func="ADD" value="317"/>
		<bonus_attr stat="MAXMP" func="ADD" value="222"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="20"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="34"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="34"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="34"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="34"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="139"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="139"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="101"/>
		<bonus_attr stat="BLOCK" func="ADD" value="101"/>
		<bonus_attr stat="PARRY" func="ADD" value="101"/>
		<bonus_attr stat="EVASION" func="ADD" value="101"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="101"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="101"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="12">
		<bonus_attr stat="MAXHP" func="ADD" value="371"/>
		<bonus_attr stat="MAXMP" func="ADD" value="260"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="22"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="38"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="38"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="38"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="38"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="149"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="149"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="112"/>
		<bonus_attr stat="BLOCK" func="ADD" value="112"/>
		<bonus_attr stat="PARRY" func="ADD" value="112"/>
		<bonus_attr stat="EVASION" func="ADD" value="112"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="112"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="112"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="13">
		<bonus_attr stat="MAXHP" func="ADD" value="425"/>
		<bonus_attr stat="MAXMP" func="ADD" value="298"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="25"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="42"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="42"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="42"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="42"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="159"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="159"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="124"/>
		<bonus_attr stat="BLOCK" func="ADD" value="124"/>
		<bonus_attr stat="PARRY" func="ADD" value="124"/>
		<bonus_attr stat="EVASION" func="ADD" value="124"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="124"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="124"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="14">
		<bonus_attr stat="MAXHP" func="ADD" value="480"/>
		<bonus_attr stat="MAXMP" func="ADD" value="336"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="27"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="46"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="46"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="46"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="46"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="168"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="168"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="135"/>
		<bonus_attr stat="BLOCK" func="ADD" value="135"/>
		<bonus_attr stat="PARRY" func="ADD" value="135"/>
		<bonus_attr stat="EVASION" func="ADD" value="135"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="135"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="135"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="15">
		<bonus_attr stat="MAXHP" func="ADD" value="534"/>
		<bonus_attr stat="MAXMP" func="ADD" value="374"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="30"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="50"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="50"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="50"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="50"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="178"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="178"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="147"/>
		<bonus_attr stat="BLOCK" func="ADD" value="147"/>
		<bonus_attr stat="PARRY" func="ADD" value="147"/>
		<bonus_attr stat="EVASION" func="ADD" value="147"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="147"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="147"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="16">
		<bonus_attr stat="MAXHP" func="ADD" value="588"/>
		<bonus_attr stat="MAXMP" func="ADD" value="412"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="32"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="54"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="54"/>
		<bonus_attr stat="PHYSICAL_CRITICAL_RESIST" func="ADD" value="54"/>
		<bonus_attr stat="MAGICAL_CRITICAL_DAMAGE_REDUCE" func="ADD" value="54"/>
		<bonus_attr stat="PHYSICAL_CRITICAL" func="ADD" value="188"/>
		<bonus_attr stat="MAGICAL_CRITICAL" func="ADD" value="188"/>
		<bonus_attr stat="PHYSICAL_ACCURACY" func="ADD" value="158"/>
		<bonus_attr stat="BLOCK" func="ADD" value="158"/>
		<bonus_attr stat="PARRY" func="ADD" value="158"/>
		<bonus_attr stat="EVASION" func="ADD" value="158"/>
		<bonus_attr stat="MAGICAL_ACCURACY" func="ADD" value="158"/>
		<bonus_attr stat="MAGICAL_RESIST" func="ADD" value="158"/>
	</luna_bonusattr>
	<luna_bonusattr buff_id="17">
    	<bonus_attr stat="MAXHP" func="ADD" value="642"/>
		<bonus_attr stat="MAXMP" func="ADD" value="450"/>
		<bonus_attr stat="HEAL_BOOST" func="ADD" value="35"/>
		<bonus_attr stat="PHYSICAL_DAMAGE" func="ADD" value="58"/>
		<bonus_attr stat="MAGICAL_DAMAGE" func="ADD" value="58"/>
