=== TheGhostGroup/aion-germany/AL-Game/data/static_data/achievement/achievement_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:element name="achievement_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="achievement_template" type="Achievements" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Achievements">
        <xs:sequence>
            <xs:element name="rewards" type="AchievementRewards" minOccurs="0" maxOccurs="1"/>
            <xs:element name="actions" type="AchievementAction" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="title" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="AchievementType"/>
        <xs:attribute name="repeat" type="AchievementRepeat"/>
        <xs:attribute name="race" type="Race"/>
        <xs:attribute name="minlevel" type="xs:int" use="required"/>
        <xs:attribute name="maxlevel" type="xs:int" use="required"/>
        <xs:attribute name="completecount" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="AchievementRewards">
        <xs:sequence>
            <xs:element name="reward_item" type="AchievementItems" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ap" type="xs:int"/>
        <xs:attribute name="gp" type="xs:int"/>
        <xs:attribute name="gold" type="xs:int"/>
        <xs:attribute name="exp" type="xs:int"/>
    </xs:complexType>
    <xs:simpleType name="AchievementType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAILY"/>
            <xs:enumeration value="WEEKLY"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AchievementRepeat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MON"/>
            <xs:enumeration value="TUE"/>
            <xs:enumeration value="THU"/>
            <xs:enumeration value="WED"/>
            <xs:enumeration value="FRI"/>
            <xs:enumeration value="SAT"/>
            <xs:enumeration value="SUN"/>
            <xs:enumeration value="ALL"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AchievementAction">
        <xs:attribute name="ids" type="IntListType"/>
    </xs:complexType>
    <xs:complexType name="AchievementItems">
        <xs:attribute name="item_id" type="xs:int"/>
        <xs:attribute name="count" type="xs:int" default="1"/>
    </xs:complexType>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/achievement/achievement_templates.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-22 15:36 -->
<achievement_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="achievement_templates.xsd">
    <achievement_template id="11" name="Daily_Mon_01_75_v70" title="1830425" type="DAILY" repeat="MON" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010045" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="12" name="Daily_Tue_01_75_v70" title="1830425" type="DAILY" repeat="TUE" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010044" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="13" name="Daily_Wed_01_75_v70" title="1830425" type="DAILY" repeat="WED" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010045" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="14" name="Daily_Thu_01_75_v70" title="1830425" type="DAILY" repeat="THU" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010044" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="15" name="Daily_Fri_01_75_v70" title="1830425" type="DAILY" repeat="FRI" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010045" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="16" name="Daily_Sat_01_75_v70" title="1830425" type="DAILY" repeat="SAT" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010044" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="17" name="Daily_Sun_01_75_v70" title="1830425" type="DAILY" repeat="SUN" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="164010045" count="1"/>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190099000" count="10"/>
            <reward_item item_id="188071672" count="1"/>
        </rewards>
        <actions ids="1002 4000 4002 2001 2005"/>
    </achievement_template>
    <achievement_template id="18" name="Weekly_01_75_v70" title="1830429" type="WEEKLY" repeat="ALL" race="PC_ALL" minlevel="1" maxlevel="75" completecount="5">
        <rewards>
            <reward_item item_id="162005047" count="1"/>
            <reward_item item_id="190200100" count="1"/>
            <reward_item item_id="188071677" count="1"/>
            <reward_item item_id="169615047" count="1"/>
            <reward_item item_id="188071668" count="1"/>
        </rewards>
        <actions ids="3002 3003 3004 3005 3006 3007 3008"/>
    </achievement_template>
    <achievement_template id="19" name="Daily_Mon_76_80_v70_L" title="1830425" type="DAILY" repeat="MON" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010046" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="3028 2014 2017 2011 1012 1013 6001 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="20" name="Daily_Tue_76_80_v70_L" title="1830425" type="DAILY" repeat="TUE" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010047" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="2022 2015 2019 2013 1012 3025 4005 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="21" name="Daily_Wed_76_80_v70_L" title="1830425" type="DAILY" repeat="WED" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010046" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="2022 2014 2017 1015 1012 3020 6001 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="22" name="Daily_Thu_76_80_v70_L" title="1830425" type="DAILY" repeat="THU" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010047" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="3028 2015 2019 2020 1012 3025 4005 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="23" name="Daily_Fri_76_80_v70_L" title="1830425" type="DAILY" repeat="FRI" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010046" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="2022 2016 2018 3024 1012 3010 6001 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="24" name="Daily_Sat_76_80_v70_L" title="1830425" type="DAILY" repeat="SAT" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010047" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="3028 2015 2019 3020 1012 1015 1013 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="25" name="Daily_Sun_76_80_v70_L" title="1830425" type="DAILY" repeat="SUN" race="ELYOS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010046" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="2022 2016 2018 2010 1012 1015 3010 4006 4008 2006 1000 5007"/>
    </achievement_template>
    <achievement_template id="26" name="Weekly_76_80_v70_L" title="1830429" type="WEEKLY" repeat="ALL" race="ELYOS" minlevel="76" maxlevel="80" completecount="7">
        <rewards>
            <reward_item item_id="190095117" count="1"/>
            <reward_item item_id="188120034" count="5"/>
            <reward_item item_id="188071675" count="1"/>
            <reward_item item_id="188071674" count="1"/>
            <reward_item item_id="162005054" count="1"/>
            <reward_item item_id="188900061" count="10"/>
        </rewards>
        <actions ids="3021 3022 3019 3026 2021 5006 4007 1011 3017 6005"/>
    </achievement_template>
    <achievement_template id="27" name="Daily_Mon_76_80_v70_D" title="1830425" type="DAILY" repeat="MON" race="ASMODIANS" minlevel="76" maxlevel="80" completecount="8">
        <rewards>
            <reward_item item_id="164010046" count="1"/>
            <reward_item item_id="190099000" count="15"/>
            <reward_item item_id="186020002" count="1"/>
            <reward_item item_id="188071673" count="1"/>
            <reward_item item_id="188900061" count="3"/>
        </rewards>
        <actions ids="3029 2014 2017 2012 1012 1014 6001 4006 4008 2006 1000 5007"/>
