=== TheGhostGroup/aion-germany/AL-Game/data/static_data/achievement/achievement_event_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:element name="achievement_event_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="achievement_event_template" type="AchievementsEvent" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="AchievementsEvent">
        <xs:sequence>
            <xs:element name="event_item" type="AchievementEventRewards" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="event_section" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="AchievementEventType"/>
        <xs:attribute name="repeat" type="AchievementEventRepeat"/>
        <xs:attribute name="race" type="Race"/>
        <xs:attribute name="minlevel" type="xs:int" use="required"/>
        <xs:attribute name="maxstage" type="xs:int" use="optional"/>
        <xs:attribute name="action_id" type="xs:int" use="optional"/>
        <xs:attribute name="active" type="xs:boolean" use="optional"/>
        <xs:attribute name="complete_point" type="xs:int" use="optional"/>
        <xs:attribute name="maxlevel" type="xs:int" use="required"/>
        <xs:attribute name="start" type="xs:dateTime" use="required"/>
        <xs:attribute name="end" type="xs:dateTime" use="required"/>
    </xs:complexType>
    <xs:complexType name="AchievementEventRewards">
        <xs:attribute name="item_id" type="xs:int"/>
        <xs:attribute name="count" type="xs:int" default="1"/>
        <xs:attribute name="stage" type="xs:int" />
    </xs:complexType>
    <xs:simpleType name="AchievementEventType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAILY"/>
            <xs:enumeration value="WEEKLY"/>
            <xs:enumeration value="EVENT_MAIN"/>
            <xs:enumeration value="EVENT_SUB"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AchievementEventRepeat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MON"/>
            <xs:enumeration value="TUE"/>
            <xs:enumeration value="THU"/>
            <xs:enumeration value="WED"/>
            <xs:enumeration value="FRI"/>
            <xs:enumeration value="SAT"/>
            <xs:enumeration value="SUN"/>
            <xs:enumeration value="ALL"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/achievement/achievement_event_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-22 15:36 -->
<achievement_event_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="achievement_event_templates.xsd">
    <achievement_event_template id="1000" name="event_treasurehunter_v70" event_section="1" type="EVENT_MAIN" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" maxstage="3" active="0" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00">
        <event_item item_id="188120004" count="3" stage="15"/>
        <event_item item_id="164012044" count="1" stage="20"/>
        <event_item item_id="164012046" count="1" stage="20"/>
        <event_item item_id="188071760" count="1" stage="65"/>
        <event_item item_id="186020037" count="3" stage="65"/>
    </achievement_event_template>
    <achievement_event_template id="1001" name="event_treasurehunter_v70_01" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="3" action_id="9000" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1002" name="event_treasurehunter_v70_02" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="3" action_id="9001" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1003" name="event_treasurehunter_v70_04" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9002" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1004" name="event_treasurehunter_v70_05" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9004" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1005" name="event_treasurehunter_v70_03" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9003" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1006" name="event_treasurehunter_v70_06" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9005" start="2018-12-06T09:00:00+00:00" end="2019-01-09T09:00:00+00:00"/>
    <achievement_event_template id="1010" name="event_alonetogether_v70" event_section="1" type="EVENT_MAIN" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1011" name="event_alonetogether_v70_01" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="0" action_id="9006" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1012" name="event_alonetogether_v70_02" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="0" action_id="9007" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1013" name="event_alonetogether_v70_03" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="0" action_id="9008" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1014" name="event_alonetogether_v70_04" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="0" action_id="9009" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1015" name="event_alonetogether_v70_05" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="0" action_id="9010" start="2018-12-27T09:00:00+00:00" end="2019-01-30T09:00:00+00:00"/>
    <achievement_event_template id="1020" name="event_live_6thpatch_v70_week01" event_section="1" type="EVENT_MAIN" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" maxstage="1" active="0" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00">
        <event_item item_id="152080095" count="10" stage="100"/>
        <event_item item_id="152080094" count="10" stage="100"/>
        <event_item item_id="188071675" count="2" stage="100"/>
        <event_item item_id="188071674" count="2" stage="100"/>
    </achievement_event_template>
    <achievement_event_template id="1021" name="event_live_6thpatch_v70_week01_01" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9011" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1022" name="event_live_6thpatch_v70_week01_02" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9012" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1023" name="event_live_6thpatch_v70_week01_03" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9013" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1024" name="event_live_6thpatch_v70_week01_04" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9014" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1025" name="event_live_6thpatch_v70_week01_05_l" event_section="0" type="EVENT_SUB" repeat="ALL" race="ELYOS" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9015" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1026" name="event_live_6thpatch_v70_week01_05_d" event_section="0" type="EVENT_SUB" repeat="ALL" race="ASMODIANS" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9016" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1027" name="event_live_6thpatch_v70_week01_06" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9017" start="2019-01-15T09:00:00+00:00" end="2019-02-06T09:00:00+00:00"/>
    <achievement_event_template id="1030" name="event_live_6thpatch_v70_week02" event_section="1" type="EVENT_MAIN" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" maxstage="1" active="0" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00">
        <event_item item_id="152080095" count="10" stage="100"/>
        <event_item item_id="152080094" count="10" stage="100"/>
        <event_item item_id="188071675" count="2" stage="100"/>
        <event_item item_id="188071674" count="2" stage="100"/>
    </achievement_event_template>
    <achievement_event_template id="1031" name="event_live_6thpatch_v70_week02_01" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9011" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1032" name="event_live_6thpatch_v70_week02_02" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="15" action_id="9012" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1033" name="event_live_6thpatch_v70_week02_03" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9013" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1034" name="event_live_6thpatch_v70_week02_04" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9014" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1035" name="event_live_6thpatch_v70_week02_05_l" event_section="0" type="EVENT_SUB" repeat="ALL" race="ELYOS" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9015" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1036" name="event_live_6thpatch_v70_week02_05_d" event_section="0" type="EVENT_SUB" repeat="ALL" race="ASMODIANS" minlevel="76" maxlevel="80" active="0" complete_point="10" action_id="9016" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="1037" name="event_live_6thpatch_v70_week02_06" event_section="0" type="EVENT_SUB" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" active="0" complete_point="20" action_id="9017" start="2019-02-06T09:00:00+00:00" end="2019-02-13T09:00:00+00:00"/>
    <achievement_event_template id="10040" name="event_toyfactory_v70" event_section="1" type="EVENT_MAIN" repeat="ALL" race="PC_ALL" minlevel="76" maxlevel="80" maxstage="3" active="0" start="2019-01-23T09:00:00+00:00" end="2019-02-27T09:00:00+00:00">
        <event_item item_id="164010077" count="9" stage="30"/>
        <event_item item_id="164010077" count="15" stage="30"/>
        <event_item item_id="164010077" count="18" stage="40"/>
    </achievement_event_template>
