=== TheGhostGroup/aion-germany/AL-Game/data/static_data/lumiel/lumiel_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
<xs:include schemaLocation="../global_types.xsd"/>
<xs:element name="lumiel_templates">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="lumiel_template" type="LumielTransformTemplate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="LumielTransformTemplate">
    <xs:sequence>
        <xs:element name="reward" type="LumielTransformReward" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required"/>
    <xs:attribute name="need_point" type="xs:int" use="required"/>
    <xs:attribute name="activate" type="xs:boolean" use="required"/>
    <xs:attribute name="name" type="xs:string"/>
</xs:complexType>
<xs:complexType name="LumielTransformReward">
    <xs:sequence>
        <xs:element name="reward_item" type="LumielRewardItem" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="grade" type="xs:int" use="required"/>
</xs:complexType>
<xs:complexType name="LumielRewardItem">
    <xs:attribute name="item_id" type="xs:int" use="required"/>
    <xs:attribute name="count" type="xs:int" use="required"/>
</xs:complexType>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/lumiel/lumiel_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-22 15:41 -->
<lumiel_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lumiel_templates.xsd">
    <lumiel_template id="1" name="reinvented_result_1" need_point="1000" activate="false">
        <reward grade="1">
            <reward_item item_id="167200011" count="1"/>
            <reward_item item_id="167200012" count="1"/>
            <reward_item item_id="167200013" count="1"/>
            <reward_item item_id="167200014" count="1"/>
            <reward_item item_id="167200015" count="1"/>
            <reward_item item_id="167200016" count="1"/>
            <reward_item item_id="167200017" count="1"/>
            <reward_item item_id="167200018" count="1"/>
            <reward_item item_id="167200019" count="1"/>
            <reward_item item_id="167200020" count="1"/>
            <reward_item item_id="167200021" count="1"/>
            <reward_item item_id="167200022" count="1"/>
            <reward_item item_id="167200023" count="1"/>
            <reward_item item_id="167200024" count="1"/>
            <reward_item item_id="167200025" count="1"/>
            <reward_item item_id="167200026" count="1"/>
            <reward_item item_id="167200027" count="1"/>
            <reward_item item_id="167200028" count="1"/>
            <reward_item item_id="167200029" count="1"/>
            <reward_item item_id="167200030" count="1"/>
            <reward_item item_id="167200031" count="1"/>
            <reward_item item_id="167200032" count="1"/>
            <reward_item item_id="167200033" count="1"/>
            <reward_item item_id="167200034" count="1"/>
            <reward_item item_id="167200035" count="1"/>
            <reward_item item_id="167200036" count="1"/>
            <reward_item item_id="167200037" count="1"/>
            <reward_item item_id="167200038" count="1"/>
            <reward_item item_id="167200039" count="1"/>
            <reward_item item_id="167200040" count="1"/>
            <reward_item item_id="167200041" count="1"/>
            <reward_item item_id="167200042" count="1"/>
            <reward_item item_id="167200043" count="1"/>
            <reward_item item_id="167200044" count="1"/>
            <reward_item item_id="167200045" count="1"/>
            <reward_item item_id="167200046" count="1"/>
            <reward_item item_id="167200047" count="1"/>
            <reward_item item_id="167200048" count="1"/>
            <reward_item item_id="167200049" count="1"/>
            <reward_item item_id="167200050" count="1"/>
            <reward_item item_id="167200051" count="1"/>
            <reward_item item_id="167200052" count="1"/>
            <reward_item item_id="167200053" count="1"/>
            <reward_item item_id="167200054" count="1"/>
            <reward_item item_id="167200055" count="1"/>
            <reward_item item_id="167200056" count="1"/>
            <reward_item item_id="167200057" count="1"/>
            <reward_item item_id="167200058" count="1"/>
            <reward_item item_id="167200059" count="1"/>
            <reward_item item_id="167200060" count="1"/>
            <reward_item item_id="167200061" count="1"/>
            <reward_item item_id="167200062" count="1"/>
            <reward_item item_id="167200063" count="1"/>
            <reward_item item_id="167200064" count="1"/>
            <reward_item item_id="167200065" count="1"/>
            <reward_item item_id="167200066" count="1"/>
            <reward_item item_id="167200067" count="1"/>
            <reward_item item_id="167200068" count="1"/>
            <reward_item item_id="167200069" count="1"/>
            <reward_item item_id="167200070" count="1"/>
            <reward_item item_id="167200071" count="1"/>
            <reward_item item_id="167200072" count="1"/>
            <reward_item item_id="167200073" count="1"/>
            <reward_item item_id="167200074" count="1"/>
            <reward_item item_id="167200075" count="1"/>
            <reward_item item_id="167200076" count="1"/>
            <reward_item item_id="167200077" count="1"/>
            <reward_item item_id="167200078" count="1"/>
            <reward_item item_id="167200079" count="1"/>
            <reward_item item_id="167200080" count="1"/>
            <reward_item item_id="167200081" count="1"/>
            <reward_item item_id="167200082" count="1"/>
        </reward>
        <reward grade="2">
            <reward_item item_id="167200083" count="1"/>
            <reward_item item_id="167200084" count="1"/>
            <reward_item item_id="167200085" count="1"/>
            <reward_item item_id="167200086" count="1"/>
            <reward_item item_id="167200087" count="1"/>
            <reward_item item_id="167200088" count="1"/>
            <reward_item item_id="167200089" count="1"/>
            <reward_item item_id="167200090" count="1"/>
            <reward_item item_id="167200091" count="1"/>
            <reward_item item_id="167200092" count="1"/>
            <reward_item item_id="167200093" count="1"/>
            <reward_item item_id="167200094" count="1"/>
            <reward_item item_id="167200095" count="1"/>
            <reward_item item_id="167200096" count="1"/>
            <reward_item item_id="167200097" count="1"/>
            <reward_item item_id="167200098" count="1"/>
            <reward_item item_id="167200099" count="1"/>
            <reward_item item_id="167200100" count="1"/>
            <reward_item item_id="167200101" count="1"/>
            <reward_item item_id="167200102" count="1"/>
            <reward_item item_id="167200103" count="1"/>
            <reward_item item_id="167200104" count="1"/>
            <reward_item item_id="167200105" count="1"/>
            <reward_item item_id="167200106" count="1"/>
            <reward_item item_id="167200107" count="1"/>
            <reward_item item_id="167200108" count="1"/>
            <reward_item item_id="167200109" count="1"/>
            <reward_item item_id="167200110" count="1"/>
            <reward_item item_id="167200111" count="1"/>
            <reward_item item_id="167200112" count="1"/>
            <reward_item item_id="167200113" count="1"/>
            <reward_item item_id="167200114" count="1"/>
            <reward_item item_id="167200115" count="1"/>
            <reward_item item_id="167200116" count="1"/>
            <reward_item item_id="167200117" count="1"/>
            <reward_item item_id="167200118" count="1"/>
            <reward_item item_id="167200119" count="1"/>
            <reward_item item_id="167200120" count="1"/>
            <reward_item item_id="167200121" count="1"/>
            <reward_item item_id="167200122" count="1"/>
            <reward_item item_id="167200123" count="1"/>
            <reward_item item_id="167200124" count="1"/>
            <reward_item item_id="167200125" count="1"/>
            <reward_item item_id="167200126" count="1"/>
            <reward_item item_id="167200127" count="1"/>
            <reward_item item_id="167200128" count="1"/>
            <reward_item item_id="167200129" count="1"/>
            <reward_item item_id="167200130" count="1"/>
            <reward_item item_id="167200131" count="1"/>
            <reward_item item_id="167200132" count="1"/>
            <reward_item item_id="167200133" count="1"/>
            <reward_item item_id="167200134" count="1"/>
            <reward_item item_id="167200135" count="1"/>
            <reward_item item_id="167200136" count="1"/>
            <reward_item item_id="167200137" count="1"/>
            <reward_item item_id="167200138" count="1"/>
            <reward_item item_id="167200139" count="1"/>
            <reward_item item_id="167200140" count="1"/>
            <reward_item item_id="167200141" count="1"/>
            <reward_item item_id="167200142" count="1"/>
            <reward_item item_id="167200143" count="1"/>
            <reward_item item_id="167200144" count="1"/>
            <reward_item item_id="167200145" count="1"/>
            <reward_item item_id="167200146" count="1"/>
            <reward_item item_id="167200147" count="1"/>
            <reward_item item_id="167200148" count="1"/>
            <reward_item item_id="167200149" count="1"/>
            <reward_item item_id="167200150" count="1"/>
            <reward_item item_id="167200151" count="1"/>
            <reward_item item_id="167200152" count="1"/>
            <reward_item item_id="167200153" count="1"/>
            <reward_item item_id="167200154" count="1"/>
        </reward>
        <reward grade="3">
            <reward_item item_id="167200155" count="1"/>
            <reward_item item_id="167200156" count="1"/>
            <reward_item item_id="167200157" count="1"/>
            <reward_item item_id="167200158" count="1"/>
            <reward_item item_id="167200159" count="1"/>
            <reward_item item_id="167200160" count="1"/>
            <reward_item item_id="167200161" count="1"/>
            <reward_item item_id="167200162" count="1"/>
            <reward_item item_id="167200163" count="1"/>
            <reward_item item_id="167200164" count="1"/>
            <reward_item item_id="167200165" count="1"/>
            <reward_item item_id="167200166" count="1"/>
            <reward_item item_id="167200167" count="1"/>
            <reward_item item_id="167200168" count="1"/>
            <reward_item item_id="167200169" count="1"/>
            <reward_item item_id="167200170" count="1"/>
            <reward_item item_id="167200171" count="1"/>
            <reward_item item_id="167200172" count="1"/>
            <reward_item item_id="167200173" count="1"/>
            <reward_item item_id="167200174" count="1"/>
