=== TheGhostGroup/aion-germany/AL-Game/data/static_data/transform/transformbook_template.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transform_book_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transform_book_template" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="grade" type="xs:int" use="required"/>
                        <xs:attribute name="skill_id" type="xs:int" use="required"/>
                        <xs:attribute name="compose_value" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/transform/transformbook_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-22 16:09 -->
<transform_book_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transformbook_template.xsd">
    <!-- Normal -->
    <transform_book_template id="982000" name="Polar Bear" grade="1" skill_id="5030" compose_value="5555"/>
    <transform_book_template id="982001" name="Anubite" grade="1" skill_id="5031" compose_value="5555"/>
    <transform_book_template id="982002" name="Pink Tiger" grade="1" skill_id="5032" compose_value="5555"/>
    <transform_book_template id="982003" name="Pirate" grade="1" skill_id="5033" compose_value="5555"/>
    <transform_book_template id="982004" name="Lepharist" grade="1" skill_id="5034" compose_value="5555"/>
    <transform_book_template id="982005" name="Graveknight" grade="1" skill_id="5035" compose_value="5555"/>
    <transform_book_template id="982006" name="Kobold" grade="1" skill_id="5036" compose_value="5555"/>
    <transform_book_template id="982007" name="White Tiger" grade="1" skill_id="5037" compose_value="5555"/>
    <transform_book_template id="982008" name="Tiger" grade="1" skill_id="5038" compose_value="5555"/>
    <transform_book_template id="982009" name="Yellow Inquin" grade="1" skill_id="5039" compose_value="5555"/>
    <transform_book_template id="982010" name="Purple Inquin" grade="1" skill_id="5040" compose_value="5555"/>
    <transform_book_template id="982011" name="Red Inquin" grade="1" skill_id="5041" compose_value="5555"/>
    <transform_book_template id="982012" name="Orange Inquin" grade="1" skill_id="5042" compose_value="5555"/>
    <transform_book_template id="982013" name="Black Inquin" grade="1" skill_id="5043" compose_value="5555"/>
    <transform_book_template id="982014" name="Green Inquin" grade="1" skill_id="5044" compose_value="5555"/>
    <transform_book_template id="982015" name="Wyvern" grade="1" skill_id="5045" compose_value="5555"/>
    <transform_book_template id="982016" name="Good-natured Shugo" grade="1" skill_id="5046" compose_value="5555"/>
    <transform_book_template id="982017" name="Powerful Panda" grade="1" skill_id="5047" compose_value="5565"/>
    <!-- Greater -->
    <transform_book_template id="982018" name="Wyvern of Victory" grade="2" skill_id="5048" compose_value="6250"/>
    <transform_book_template id="982019" name="Shugo" grade="2" skill_id="5049" compose_value="6250"/>
    <transform_book_template id="982020" name="Super Shugo" grade="2" skill_id="5050" compose_value="6250"/>
    <transform_book_template id="982021" name="Luna Patrol" grade="2" skill_id="5051" compose_value="6250"/>
    <transform_book_template id="982022" name="Jester" grade="2" skill_id="5052" compose_value="6250"/>
    <transform_book_template id="982023" name="Anubite Warrior" grade="2" skill_id="5053" compose_value="6250"/>
    <transform_book_template id="982024" name="Doberman" grade="2" skill_id="5054" compose_value="6250"/>
    <transform_book_template id="982025" name="Tin" grade="2" skill_id="5055" compose_value="6250"/>
    <transform_book_template id="982026" name="Chihuahua" grade="2" skill_id="5056" compose_value="6250"/>
    <transform_book_template id="982027" name="Pomeranian" grade="2" skill_id="5057" compose_value="6250"/>
    <transform_book_template id="982028" name="Mau" grade="2" skill_id="5058" compose_value="6250"/>
    <transform_book_template id="982029" name="Test Subject" grade="2" skill_id="5059" compose_value="6250"/>
    <transform_book_template id="982030" name="Krall" grade="2" skill_id="5060" compose_value="6250"/>
    <transform_book_template id="982031" name="Rabbit Bandit" grade="2" skill_id="5061" compose_value="6250"/>
    <transform_book_template id="982051" name="Naughty Rabbit" grade="2" skill_id="5295" compose_value="6250"/>
    <transform_book_template id="982052" name="Golden Tin" grade="2" skill_id="5296" compose_value="6250"/>
    <!-- Ancient -->
    <transform_book_template id="982032" name="Baa" grade="3" skill_id="5062" compose_value="5266"/>
    <transform_book_template id="982033" name="Desert Fox" grade="3" skill_id="5063" compose_value="5263"/>
    <transform_book_template id="982034" name="Tiamat Dragonbound" grade="3" skill_id="5064" compose_value="5263"/>
    <transform_book_template id="982035" name="Tarha" grade="3" skill_id="5065" compose_value="5263"/>
    <transform_book_template id="982036" name="Black Mane" grade="3" skill_id="5066" compose_value="5263"/>
    <transform_book_template id="982037" name="Cat" grade="3" skill_id="5067" compose_value="5263"/>
    <transform_book_template id="982038" name="Popoku" grade="3" skill_id="5068" compose_value="5263"/>
    <transform_book_template id="982039" name="Aquan" grade="3" skill_id="5069" compose_value="5263"/>
    <transform_book_template id="982040" name="Tiamat Drakan" grade="3" skill_id="5070" compose_value="5263"/>
    <transform_book_template id="982041" name="Beritra Drakan" grade="3" skill_id="5071" compose_value="5263"/>
    <transform_book_template id="982042" name="Ereshkigal Drakan" grade="3" skill_id="5072" compose_value="5263"/>
    <transform_book_template id="982053" name="Pixel" grade="3" skill_id="5297" compose_value="5263"/>
    <transform_book_template id="982054" name="Light Field Warden" grade="3" skill_id="5298" compose_value="5263"/>
    <transform_book_template id="982055" name="Dark Field Warden" grade="3" skill_id="5299" compose_value="5263"/>
    <transform_book_template id="982056" name="Minion of Oblivion" grade="3" skill_id="5300" compose_value="5263"/>
    <transform_book_template id="982057" name="Ereshkigal's Apostle" grade="3" skill_id="5301" compose_value="5263"/>
    <transform_book_template id="982058" name="Beritra's Apostle" grade="3" skill_id="5302" compose_value="5263"/>
    <transform_book_template id="982059" name="Tiamat's Apostle" grade="3" skill_id="5303" compose_value="5263"/>
    <transform_book_template id="982066" name="Blurs of Colour" grade="3" skill_id="5365" compose_value="5263"/>
    <transform_book_template id="982100" name="Dr Murr" grade="3" skill_id="6311" compose_value="0"/>
    <transform_book_template id="982101" name="Sister Meow" grade="3" skill_id="6312" compose_value="0"/>
    <transform_book_template id="982103" name="Hanbok Baa" grade="3" skill_id="5676" compose_value="0"/>
    <transform_book_template id="982104" name="Hanbok Moo" grade="3" skill_id="5677" compose_value="0"/>
    <!-- Legendary -->
    <transform_book_template id="982043" name="Hamerun" grade="4" skill_id="5375" compose_value="7740"/>
    <transform_book_template id="982044" name="Bollvig" grade="4" skill_id="5074" compose_value="7740"/>
    <transform_book_template id="982045" name="Kromede" grade="4" skill_id="5376" compose_value="7740"/>
    <transform_book_template id="982046" name="Tahabata" grade="4" skill_id="5076" compose_value="7740"/>
    <transform_book_template id="982047" name="Mastarius" grade="4" skill_id="5077" compose_value="7740"/>
    <transform_book_template id="982048" name="Veille" grade="4" skill_id="5078" compose_value="7740"/>
    <transform_book_template id="982049" name="Sita" grade="4" skill_id="5079" compose_value="7740"/>
    <transform_book_template id="982060" name="Weda" grade="4" skill_id="5373" compose_value="7740"/>
    <transform_book_template id="982061" name="Prigga" grade="4" skill_id="5305" compose_value="7740"/>
    <transform_book_template id="982062" name="Grendal" grade="4" skill_id="5306" compose_value="7740"/>
    <transform_book_template id="982063" name="Valiant Hanbok Pixel" grade="4" skill_id="5357" compose_value="0"/>
    <transform_book_template id="982064" name="Wise Hanbok Pixel" grade="4" skill_id="5358" compose_value="0"/>
    <transform_book_template id="982065" name="Cunning Hanbok Pixel" grade="4" skill_id="5359" compose_value="0"/>
    <transform_book_template id="982067" name="Irunin" grade="4" skill_id="5374" compose_value="7738"/>
    <transform_book_template id="982068" name="Israphel's Apostle" grade="4" skill_id="5687" compose_value="2477"/>
    <transform_book_template id="982069" name="Marchutan's Apostle" grade="4" skill_id="5688" compose_value="2477"/>
    <transform_book_template id="982070" name="Zikel's Apostle" grade="4" skill_id="5689" compose_value="2477"/>
    <transform_book_template id="982071" name="Kaisinel's Apostle" grade="4" skill_id="5690" compose_value="2477"/>
    <transform_book_template id="982072" name="Siel's Apostle" grade="4" skill_id="5691" compose_value="2477"/>
    <transform_book_template id="982073" name="Nezekan's Apostle" grade="4" skill_id="5692" compose_value="2477"/>
    <transform_book_template id="982078" name="Raging Hanbok Pixel" grade="4" skill_id="5968" compose_value="0"/>
    <transform_book_template id="982079" name="Frightchamun" grade="4" skill_id="6352" compose_value="0"/>
    <transform_book_template id="982080" name="Jack Nox" grade="4" skill_id="6353" compose_value="0"/>
    <transform_book_template id="982081" name="Frankenshock" grade="4" skill_id="6354" compose_value="0"/>
    <transform_book_template id="982082" name="Vampirina" grade="4" skill_id="6355" compose_value="0"/>
    <transform_book_template id="982086" name="Ariel's Apostle" grade="4" skill_id="6614" compose_value="0"/>
    <transform_book_template id="982087" name="Azphel's Apostle" grade="4" skill_id="6615" compose_value="0"/>
    <transform_book_template id="982088" name="Yustiel's Apostle" grade="4" skill_id="6616" compose_value="0"/>
    <transform_book_template id="982089" name="Triniel's Apostle" grade="4" skill_id="6617" compose_value="0"/>
    <transform_book_template id="982090" name="Vaizel's Apostle" grade="4" skill_id="6618" compose_value="0"/>
