=== TheGhostGroup/aion-germany/AL-Game/data/static_data/transform/transform_collection_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
    <xs:include schemaLocation="../stats/stats.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="transform_collection_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transform_collection_template" type="TransformCollectionTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TransformCollectionTemplate">
        <xs:sequence>
            <xs:element name="physical_bonus" type="CollectionAttr" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="magical_bonus" type="CollectionAttr" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="required" type="CollectionRequired" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="need_count" type="xs:int" use="optional"/>
        <xs:attribute name="reward_skill" type="xs:int" use="optional"/>
    </xs:complexType>
    <xs:complexType name="CollectionAttr">
        <xs:attribute name="name" type="modifiersenum" use="required"/>
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="CollectionRequired">
        <xs:attribute name="ids" type="IntListType"/>
    </xs:complexType>
</xs:schema>

=== TheGhostGroup/aion-germany/AL-Game/data/static_data/transform/transform_collection_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-22 16:10 -->
<transform_collection_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transform_collection_templates.xsd">
    <transform_collection_template id="1">
        <physical_bonus name="PARRY" value="108"/>
        <magical_bonus name="PARRY" value="108"/>
        <required ids="982051 982024"/>
    </transform_collection_template>
    <transform_collection_template id="2">
        <physical_bonus name="BLOCK" value="108"/>
        <magical_bonus name="BLOCK" value="108"/>
        <required ids="982052 982018"/>
    </transform_collection_template>
    <transform_collection_template id="3">
        <physical_bonus name="PHYSICAL_DEFENSE" value="38"/>
        <magical_bonus name="PHYSICAL_DEFENSE" value="38"/>
        <required ids="982051 982031 982052 982025"/>
    </transform_collection_template>
    <transform_collection_template id="4">
        <physical_bonus name="MAGICAL_DEFEND" value="38"/>
        <magical_bonus name="MAGICAL_DEFEND" value="38"/>
        <required ids="982052 982025 982022 982021"/>
    </transform_collection_template>
    <transform_collection_template id="5">
        <physical_bonus name="MAGICAL_RESIST" value="215"/>
        <magical_bonus name="MAGICAL_RESIST" value="215"/>
        <required ids="982032 982053 982038 982027 982026"/>
    </transform_collection_template>
    <transform_collection_template id="6">
        <physical_bonus name="EVASION" value="215"/>
        <magical_bonus name="EVASION" value="215"/>
        <required ids="982030 982028 982036 982039 982035 982056"/>
    </transform_collection_template>
    <transform_collection_template id="7">
        <physical_bonus name="MAGICAL_RESIST" value="108"/>
        <magical_bonus name="MAGICAL_RESIST" value="108"/>
        <required ids="982054 982019 982020"/>
    </transform_collection_template>
    <transform_collection_template id="8">
        <physical_bonus name="MAGICAL_DEFEND" value="76"/>
        <magical_bonus name="MAGICAL_DEFEND" value="76"/>
        <required ids="982055 982019 982020"/>
    </transform_collection_template>
    <transform_collection_template id="9">
        <physical_bonus name="PHYSICAL_DEFENSE" value="76"/>
        <magical_bonus name="PHYSICAL_DEFENSE" value="76"/>
        <required ids="982056 982023 982029 982034"/>
    </transform_collection_template>
    <transform_collection_template id="10">
        <physical_bonus name="BLOCK" value="538"/>
        <magical_bonus name="BLOCK" value="538"/>
        <required ids="982040 982059 982034 982046"/>
    </transform_collection_template>
    <transform_collection_template id="11">
        <physical_bonus name="PARRY" value="538"/>
        <magical_bonus name="PARRY" value="538"/>
        <required ids="982042 982057 982034 982061"/>
    </transform_collection_template>
    <transform_collection_template id="12">
        <physical_bonus name="MAGICAL_ACCURACY" value="110"/>
        <magical_bonus name="MAGICAL_ACCURACY" value="110"/>
        <required ids="982041 982058 982034 982049"/>
    </transform_collection_template>
    <transform_collection_template id="13">
        <physical_bonus name="PHYSICAL_ACCURACY" value="110"/>
        <magical_bonus name="PHYSICAL_ACCURACY" value="110"/>
        <required ids="982059 982057 982058 982043 982040 982041"/>
    </transform_collection_template>
    <transform_collection_template id="14">
        <physical_bonus name="MAGICAL_ACCURACY" value="331"/>
        <magical_bonus name="MAGICAL_ACCURACY" value="331"/>
        <required ids="982060 982047 982048"/>
    </transform_collection_template>
    <transform_collection_template id="15">
        <physical_bonus name="PHYSICAL_ATTACK" value="78"/>
        <magical_bonus name="PHYSICAL_ATTACK" value="78"/>
        <required ids="982060 982061 982062"/>
    </transform_collection_template>
    <transform_collection_template id="16">
        <physical_bonus name="EVASION" value="538"/>
        <magical_bonus name="EVASION" value="538"/>
        <required ids="982056 982059 982046 982047 982043 982044"/>
    </transform_collection_template>
    <transform_collection_template id="17">
        <physical_bonus name="PHYSICAL_DEFENSE" value="190"/>
        <magical_bonus name="PHYSICAL_DEFENSE" value="190"/>
        <required ids="982060 982061 982062 982045 982048 982049"/>
    </transform_collection_template>
    <transform_collection_template id="18">
        <physical_bonus name="PHYSICAL_CRITICAL" value="308"/>
        <magical_bonus name="PHYSICAL_CRITICAL" value="308"/>
        <required ids="982056 982062 982049 982046"/>
    </transform_collection_template>
    <transform_collection_template id="19">
        <physical_bonus name="MAGICAL_RESIST" value="538"/>
        <magical_bonus name="MAGICAL_RESIST" value="538"/>
        <required ids="982059 982057 982058 982046 982049 982061"/>
    </transform_collection_template>
    <transform_collection_template id="20">
        <physical_bonus name="PHYSICAL_ACCURACY" value="551"/>
        <magical_bonus name="PHYSICAL_ACCURACY" value="551"/>
        <required ids="982037 982055 982061 982047 982045 982043"/>
    </transform_collection_template>
    <transform_collection_template id="21">
        <physical_bonus name="MAGICAL_ACCURACY" value="551"/>
        <magical_bonus name="MAGICAL_ACCURACY" value="551"/>
        <required ids="982032 982057 982062 982048 982046 982044"/>
    </transform_collection_template>
    <transform_collection_template id="22">
        <physical_bonus name="PHYSICAL_ACCURACY" value="331"/>
        <magical_bonus name="PHYSICAL_ACCURACY" value="331"/>
        <required ids="982054 982048 982055 982047"/>
    </transform_collection_template>
    <transform_collection_template id="23">
        <physical_bonus name="MAGICAL_DEFEND" value="190"/>
        <magical_bonus name="MAGICAL_DEFEND" value="190"/>
        <required ids="982060 982061 982062 982043 982045 982046"/>
    </transform_collection_template>
    <transform_collection_template id="24">
        <physical_bonus name="PHYSICAL_CRITICAL" value="513"/>
        <magical_bonus name="PHYSICAL_CRITICAL" value="513"/>
        <required ids="982054 982055 982047 982048 982060 982050"/>
    </transform_collection_template>
    <transform_collection_template id="25">
        <physical_bonus name="EVASION" value="108"/>
        <magical_bonus name="EVASION" value="108"/>
    </transform_collection_template>
    <transform_collection_template id="26">
        <physical_bonus name="HEAL_BOOST" value="49"/>
        <magical_bonus name="HEAL_BOOST" value="49"/>
    </transform_collection_template>
    <transform_collection_template id="27">
        <physical_bonus name="HEAL_BOOST" value="123"/>
        <magical_bonus name="HEAL_BOOST" value="123"/>
    </transform_collection_template>
    <transform_collection_template id="28">
        <physical_bonus name="PHYSICAL_ATTACK" value="195"/>
        <magical_bonus name="PHYSICAL_ATTACK" value="195"/>
    </transform_collection_template>
    <transform_collection_template id="29">
        <physical_bonus name="PHYSICAL_DEFENSE" value="152"/>
        <magical_bonus name="PHYSICAL_DEFENSE" value="152"/>
        <required ids="982026 982034 982057 982063"/>
    </transform_collection_template>
    <transform_collection_template id="30">
        <physical_bonus name="MAGICAL_DEFEND" value="152"/>
        <magical_bonus name="MAGICAL_DEFEND" value="152"/>
        <required ids="982052 982053 982056 982064"/>
    </transform_collection_template>
    <transform_collection_template id="31">
        <physical_bonus name="PHYSICAL_ATTACK" value="152"/>
        <magical_bonus name="PHYSICAL_ATTACK" value="152"/>
        <required ids="982054 982055 982034 982065"/>
    </transform_collection_template>
    <transform_collection_template id="32">
        <physical_bonus name="PHYSICAL_CRITICAL" value="411"/>
        <magical_bonus name="PHYSICAL_CRITICAL" value="411"/>
        <required ids="982063 982064 982065"/>
    </transform_collection_template>
    <transform_collection_template id="33">
        <physical_bonus name="PHYSICAL_ACCURACY" value="220"/>
        <magical_bonus name="PHYSICAL_ACCURACY" value="220"/>
        <required ids="982020 982018 982066"/>
    </transform_collection_template>
    <transform_collection_template id="34">
        <physical_bonus name="PHYSICAL_ATTACK" value="171"/>
        <magical_bonus name="PHYSICAL_ATTACK" value="171"/>
        <required ids="982067 982043 982044 982035 982039 982056"/>
    </transform_collection_template>
    <transform_collection_template id="35">
        <physical_bonus name="MAGICAL_RESIST" value="323"/>
        <magical_bonus name="MAGICAL_RESIST" value="323"/>
        <required ids="982068 982060 982066"/>
    </transform_collection_template>
    <transform_collection_template id="36">
        <physical_bonus name="PHYSICAL_CRITICAL" value="154"/>
        <magical_bonus name="PHYSICAL_CRITICAL" value="154"/>
        <required ids="982069 982045 982044 982036"/>
    </transform_collection_template>
    <transform_collection_template id="37">
        <physical_bonus name="EVASION" value="323"/>
        <magical_bonus name="EVASION" value="323"/>
        <required ids="982070 982049 982056"/>
    </transform_collection_template>
    <transform_collection_template id="38">
        <physical_bonus name="PHYSICAL_ACCURACY" value="331"/>
        <magical_bonus name="PHYSICAL_ACCURACY" value="331"/>
        <required ids="982071 982061 982042 982057"/>
    </transform_collection_template>
    <transform_collection_template id="39">
        <physical_bonus name="PHYSICAL_CRITICAL" value="30"/>
